### ISSUE TITLE
Expanding Categories

### ISSUE THREAD

**Issue by MeganBIN** [Stars2Apples/Support#14] opened 2021-09-22 13:23 UTC
I believe there was a recent update to my Stars 2 Apples app.  When the update happened it shows three dots at the end of a category which is meant to expand the category further.  However, you can click until you're blue and it never expands.  It works on some, but not all.  I have found that my most used category - Favorites - does not expand.  I've included a picture of the three dots I'm referencing.  I posted on our main FB page, and someone else agreed that it is not working.  They said to send it here.
Thanks!  Megan

![IMG_4646](https://user-images.githubusercontent.com/91201137/134351536-c618bdd7-241b-4144-a6df-b9b09aa3f7df.jpg)

**Comment by ianclawson** [comment] 2021-09-23 07:18
Thank you for reporting this @MeganBIN, and for reporting it here!

I was just able to reproduce it for the favorites row, you're right that it does not expand. I'm not sure what might be going wrong there but because it's easily reproducible, I should be able to get to the bottom of it and submit an update very quickly. I will let you know once that's updated!

**Comment by MeganBIN** [comment] 2021-09-23 12:28
Thank you!!

**Comment by ianclawson** [comment] 2021-09-23 15:48
@MeganBIN I just pushed the release button on a new version (1.5.1) that should fix this. Keep an eye out for that update, it should become available for you in the next few hours. Once you've updated can you let me know if this fixes the issue for you?

**Comment by ianclawson** [comment] 2021-09-24 16:06
Closing this issue for now as it appears to be fixed. Feel free to reopen it if you (or anyone) see differently on v1.5.1. 🙂

**Closed as completed** 2021-09-24 16:06 UTC
Labels: bug
